### ISSUE TITLE
'tokio-runtime-worker' panicked at 'Could not get tendermint status: serde parse error

### ISSUE THREAD

**Issue by Cordtus** [nomic-io/nomic#122]
Attempt starting new install, running latest rust nightly `rustc 1.63.0-nightly (50b00252a 2022-06-06)` immediately panics and fails.
```
$ nomic start
Configuring node for state sync...
Getting bootstrap state for Tendermint light client...
thread 'tokio-runtime-worker' panicked at 'Could not get tendermint status: serde parse error

Caused by:
    expected value at line 1 column 1

Location:
    /home/sv/.cargo/registry/src/github.com-1ecc6299db9ec823/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9', src/bin/nomic.rs:316:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
App Error: panic
```

Full Backtrace details:

```
$ bash -c "RUST_BACKTRACE=full nomic start"
Configuring node for state sync...
Getting bootstrap state for Tendermint light client...
thread 'tokio-runtime-worker' panicked at 'Could not get tendermint status: serde parse error

Caused by:
    expected value at line 1 column 1

Location:
    /home/sv/.cargo/registry/src/github.com-1ecc6299db9ec823/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9

Stack backtrace:
   0: core::ops::function::Fn::call
   1: eyre::capture_handler
   2: eyre::error::<impl eyre::Report>::msg
   3: <flex_error::source::DisplayOnly<E> as flex_error::source::ErrorSource<Tracer>>::error_details
   4: tendermint_rpc::error::Error::serde
   5: tendermint_rpc::response::Response::from_string
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: std::thread::local::LocalKey<T>::with
  10: futures_executor::local_pool::block_on
  11: nomic::configure_for_statesync
  12: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  13: tokio::runtime::task::core::CoreStage<T>::poll
  14: tokio::runtime::task::harness::Harness<T,S>::poll
  15: tokio::runtime::blocking::pool::Inner::run
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
  17: core::ops::function::FnOnce::call_once{{vtable.shim}}
  18: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/alloc/src/boxed.rs:1951:9
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/alloc/src/boxed.rs:1951:9
  20: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/sys/unix/thread.rs:108:17
  21: start_thread
  22: clone
', src/bin/nomic.rs:316:14
stack backtrace:
   0:     0x55f5efc1f75d - std::backtrace_rs::backtrace::libunwind::trace::h2a8892c156585d66
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55f5efc1f75d - std::backtrace_rs::backtrace::trace_unsynchronized::h918c401bc86eed40
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f5efc1f75d - std::sys_common::backtrace::_print_fmt::h2a52b4cb52dc84fb
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55f5efc1f75d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2f5ce3ea50e5b1d6
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55f5efc4696c - core::fmt::write::h48a5b18f44037270
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/core/src/fmt/mod.rs:1196:17
   5:     0x55f5efc18fe1 - std::io::Write::write_fmt::h1d1b08935a2fcf4b
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/io/mod.rs:1654:15
   6:     0x55f5efc20d95 - std::sys_common::backtrace::_print::h46d4f4f2d0dbcce0
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55f5efc20d95 - std::sys_common::backtrace::print::h8334e6fa27a1dde4
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55f5efc20d95 - std::panicking::default_hook::{{closure}}::hc13c7ff820b0fe22
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/panicking.rs:295:22
   9:     0x55f5efc20ab6 - std::panicking::default_hook::h100ba67c99329739
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/panicking.rs:314:9
  10:     0x55f5efc21326 - std::panicking::rust_panic_with_hook::h0a6a04da5fd1d45f
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/panicking.rs:698:17
  11:     0x55f5efc21217 - std::panicking::begin_panic_handler::{{closure}}::h55242fd43a581580
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/panicking.rs:588:13
  12:     0x55f5efc1fc14 - std::sys_common::backtrace::__rust_end_short_backtrace::h53771d999c075964
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55f5efc20f49 - rust_begin_unwind
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/panicking.rs:584:5
  14:     0x55f5eeb94443 - core::panicking::panic_fmt::h1a17f733294f4ffb
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/core/src/panicking.rs:142:14
  15:     0x55f5eeb94533 - core::result::unwrap_failed::hb96e0128b0d3cf3e
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/core/src/result.rs:1805:5
  16:     0x55f5eec7c115 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbfc4ca37d2e0ea4a
  17:     0x55f5eed605c1 - std::thread::local::LocalKey<T>::with::h945f017f0fd77ee0
  18:     0x55f5eef32a6d - futures_executor::local_pool::block_on::hb7ad54143a7dd4e8
  19:     0x55f5eed11635 - nomic::configure_for_statesync::h11e4b4aded29ea15
  20:     0x55f5eeeea44f - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h73e38f3b64471900
  21:     0x55f5eece05eb - tokio::runtime::task::core::CoreStage<T>::poll::h4f7f935d64693a23
  22:     0x55f5eede6260 - tokio::runtime::task::harness::Harness<T,S>::poll::h6bb64ff469403bed
  23:     0x55f5efb92805 - tokio::runtime::blocking::pool::Inner::run::h9653a3b10a6ee03e
  24:     0x55f5efb974c7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h43b8945bc4261c99
  25:     0x55f5efb9a3ea - core::ops::function::FnOnce::call_once{{vtable.shim}}::had19396efb2580cd
  26:     0x55f5efc26e23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha070fd431c3387e9
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/alloc/src/boxed.rs:1951:9
  27:     0x55f5efc26e23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd87ab2d0201316b5
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/alloc/src/boxed.rs:1951:9
  28:     0x55f5efc26e23 - std::sys::unix::thread::Thread::new::thread_start::ha32118aaa6c8a9be
                               at /rustc/50b00252aeb77b10db04d65dc9e12ce758def4b5/library/std/src/sys/unix/thread.rs:108:17
  29:     0x7fc7edb82609 - start_thread
  30:     0x7fc7ed753133 - clone
  31:                0x0 - <unknown>
App Error: panic
```

**Comment by mappum** [comment]
It looks like the Polkachu node is down, which is being used for bootstrapping the light client. For now, you can simply comment out line 225 in src/bin/nomic.rs.

**Comment by faddat** [comment]
ahhhhhhh wonderful :D

**Comment by faddat** [comment]
I saw the code comments and will try to solve... rust amatur here, though

**Comment by mappum** [comment]
> ahhhhhhh wonderful :D
> 
> Matt, is it possible to add additional nodes to that bootstrap step so that we could have.... let's say... 100 nodes to bootstrap from?

Would definitely love to make this resilient and come with a large bootstrap list. It currently fails if any of them are offline or serve conflicting results, but this could be made to just assume some threshold (e.g. 90%) agrees.

**Comment by mappum** [comment]
Since this issue, the boostrap mechanism has been made more resilient (it will succeed if up to 50% of the bootstrap nodes are reachable), and the next step is to just get validators to add themselves to the list.
